from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from database import Base


class CaseStudy(Base):
    __tablename__ = "case_studies"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    # UI: Project Name
    title: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
    )

    # UI: Template
    template: Mapped[str] = mapped_column(
        String(100),
        default="product_designer",
        nullable=False,
    )

    # User raw input
    raw_note: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # AI generated case (JSON string)
    generated_json: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # draft | completed | archived
    status: Mapped[str] = mapped_column(
        String(30),
        default="draft",
        nullable=False,
    )

    # For future regenerate/version flows
    version: Mapped[int] = mapped_column(
        default=1,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow,
        onupdate=datetime.utcnow,
    )

    images: Mapped[list["CaseImage"]] = relationship(
        back_populates="case",
        cascade="all, delete-orphan",
    )


class CaseImage(Base):
    __tablename__ = "case_images"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
    )

    case_id: Mapped[int] = mapped_column(
        ForeignKey("case_studies.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    section_key: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
    )

    # Internal URL generated by the upload endpoint.
    location: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
    )

    # Original uploaded filename.
    name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    # UI metadata that must survive refresh/redeploy.
    evidence_type: Mapped[str] = mapped_column(
        String(50),
        default="Other",
        nullable=False,
    )

    caption: Mapped[str] = mapped_column(
        Text,
        default="",
        nullable=False,
    )

    sort_order: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
    )

    case: Mapped["CaseStudy"] = relationship(
        back_populates="images",
    )
